### ISSUE TITLE
Yandex.ru shows previews only after second reload

### ISSUE THREAD

**Issue by GwenDragon** [GwenDragon/searchenginepreview#6]
There is a load problem of previews on russian Yandex.
The previews are not shown at first call of searches. 
A reload with F5 shows the previews.

I'll try to investigate.

**Comment by bsergeytpp** [comment]
Hello, Yandex changed its search string, so now it is "_search_" and not "_yandsearch_".

Did some debugging on this issue and seems that the **PreviewsInWebpage** function fires earlier than response coming in **fetchOptions** so _ENABLE_PREVIEW_ICON_ and _ENABLE_IMAGE_INSERT_ are still undefined.

**PreviewsInWebpage**  calls **addThumb** and as those two consts are undefined no conditional code in **addThumb** is executed.

This code in **PreviewsInWebpage** works for me, but i'm new to chrome extension API, so there could be another simple fix.
```
if(ENABLE_PREVIEW_ICON || ENABLE_IMAGE_INSERT) {
	thumbshots(url);
}
```
Hope this helps in some way.

**Comment by GwenDragon** [comment]
Thanks for report.
I will check this and release a fixed version.

**Comment by GwenDragon** [comment]
This solved the Yandex bug.
